* questions
1. Does LRFS impact MFS and OS
   1.
   2.
* Data points
** Margins
*** Gross positive
1. # 49 1990 low grade shoulder girdle
2. # 112 foot phalanx,high grade, initially curretted 2005 JSW
3. # 153 pelvis high grade 1995
4. LR at presentation and again# 191 high pelvis ramus 1995
5. LR # 249 high pelvis ilium 2004
6. # 258 high pelvis ilium 1994
7. LR # 274 dediff distal femur 2003
8. # 287 scapula dediff 2001
*** Micro-positive
1. LR## 4 LR, # 54,pathfrac and LR high,#132 LR at presentation.# 152
   Rads and LR at presentation.# 194 Low, LR at presentation.# 239
   high, pathfrac,LR and Met#244 dediff pathfrac,LR, Met.#281 LR at
   presentation,met,#302 high
2. Low Grade# 45,57,58,104,141,163,164,172,196,254
3. Rads #135,138 remote rads,149.206,223
4. Met at presentation #238 dediff # 265,268 high,277,282 high,293 met
   presentation,met.#309 rads,multiple mets

* names(csatest)
 [1] "dob"                        "age_surgery"
 [3] "sex"                        "diagnosis"
 [5] "site"                       "anatomy"
 [7] "presenting_status"          "date_biopsy"
 [9] "prior_surgery"              "type_surgery"
[11] "date_surgery"               "type_closure"
[13] "radiation"                  "chemotherapy"
[15] "size"                       "grade"
[17] "margin"                     "necrosis"
[19] "complications"              "surgery_complications"
[21] "date_surgery_complications" "relapse1_type"
[23] "relapse1_date"              "relapse1_type_surgery"
[25] "relapse1_date_surgery"      "relapse1_radiation"
[27] "relapse1_chemotherapy"      "relapse2_type"
[29] "relapse2_date"              "relapse2_type_surgery"
[31] "relapse2_date_surgery"      "relapse2_radiation"
[33] "relapse2_chemotherapy"      "relapse3_type"
[35] "relapse3_date"              "relapse3_type_surgery"
[37] "relapse3_date_surgery"      "relapse3_radiation"
[39] "relapse3_chemotherapy"      "status"
[41] "date_status"                "dfs_months"
[43] "os_months"                  "comments"
[45] "type_chondrosarcoma"        "body_region"
[47] "tiergrade"                  "margintype"
[49] "radiation_status"           "pathfrac_presentation"
[51] "met_presentation"           "lr_presentation"
[53] "lr"                         "met"
[55] "lr2"                        "met2"
[57] "met3"                       "lr3"
[59] "age_sx"                     "lrfs"
[61] "mfs"                        "os"
[63] "age_y"                      "os_y"
[65] "mfs_y"                      "lrfs_y"
[67] "lrstatus"                   "metstatus"
* Time in years Univariate LM
** LRFS
*** summary (lm(lrfs_y~age_y,data=csatest))

Call:
lm(formula = lrfs_y ~ age_y, data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-9.0334 -4.5846 -0.2407  3.1526 17.8609

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept) 11.06516    0.91852  12.047  < 2e-16 ***
age_y       -0.06508    0.01846  -3.526 0.000487 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.59 on 308 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.03879,	Adjusted R-squared:  0.03567
F-statistic: 12.43 on 1 and 308 DF,  p-value: 0.0004868
*** summary (lm(lrfs_y~factor(pathfrac_presentation),data=csatest))

Call:
lm(formula = lrfs_y ~ factor(pathfrac_presentation), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-8.3192 -4.2356 -0.3904  3.1137 18.4561

Coefficients:
                                 Estimate Std. Error t value Pr(>|t|)
(Intercept)                        8.3658     0.3276  25.535  < 2e-16 ***
factor(pathfrac_presentation)yes  -4.8831     1.2047  -4.053  6.4e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.56 on 309 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.05048,	Adjusted R-squared:  0.04741
F-statistic: 16.43 on 1 and 309 DF,  p-value: 6.397e-05
*** summary (lm(lrfs_y~factor(margintype),data=csatest))

Call:
lm(formula = lrfs_y ~ factor(margintype), data = csatest)

Residuals:
   Min     1Q Median     3Q    Max
-8.007 -4.799 -0.538  3.442 15.999

Coefficients:
                                 Estimate Std. Error t value Pr(>|t|)
(Intercept)                         9.176      2.534   3.621 0.000348 ***
factor(margintype)gross_positive   -4.222      3.231  -1.307 0.192301
factor(margintype)micro_positive   -1.084      2.653  -0.408 0.683236
factor(margintype)negative         -1.123      2.563  -0.438 0.661456
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.667 on 284 degrees of freedom
  (24 observations deleted due to missingness)
Multiple R-squared:  0.008932,	Adjusted R-squared:  -0.001537
F-statistic: 0.8532 on 3 and 284 DF,  p-value: 0.4659
*** summary (lm(lrfs_y~factor(tiergrade),data=csatest))

Call:
lm(formula = lrfs_y ~ factor(tiergrade), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-8.4580 -4.7588 -0.1536  3.0533 18.3725

Coefficients:
                      Estimate Std. Error t value Pr(>|t|)
(Intercept)             5.6149     0.7706   7.286 2.69e-12 ***
factor(tiergrade)high   2.8345     0.8757   3.237  0.00134 **
factor(tiergrade)low    2.9910     1.0040   2.979  0.00312 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.61 on 308 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.0364,	Adjusted R-squared:  0.03014
F-statistic: 5.817 on 2 and 308 DF,  p-value: 0.003314
***  summary (lm(lrfs_y~factor(body_region),data=csatest))

Call:
lm(formula = lrfs_y ~ factor(body_region), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-9.4090 -4.6360 -0.9651  3.2749 19.2538

Coefficients:
                             Estimate Std. Error t value Pr(>|t|)
(Intercept)                   7.56816    0.59556  12.708   <2e-16 ***
factor(body_region)flat_bone  2.44629    1.14979   2.128   0.0342 *
factor(body_region)Hand_Foot  2.83805    1.57570   1.801   0.0727 .
factor(body_region)Long_Bone  0.07197    0.73431   0.098   0.9220
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.65 on 307 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.02584,	Adjusted R-squared:  0.01632
F-statistic: 2.714 on 3 and 307 DF,  p-value: 0.04499


** MFS
*** summary (lm(mfs_y~age_y,data=csatest))

Call:
lm(formula = mfs_y ~ age_y, data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-8.8980 -4.8272 -0.1905  3.4018 18.1669

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept) 10.53964    0.93518  11.270  < 2e-16 ***
age_y       -0.05829    0.01878  -3.103  0.00209 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.694 on 307 degrees of freedom
  (3 observations deleted due to missingness)
Multiple R-squared:  0.03041,	Adjusted R-squared:  0.02726
F-statistic:  9.63 on 1 and 307 DF,  p-value: 0.002092
*** summary (lm(mfs_y~factor(pathfrac_presentation),data=csatest))

Call:
lm(formula = mfs_y ~ factor(pathfrac_presentation), data = csatest)

Residuals:
   Min     1Q Median     3Q    Max
-8.127 -4.817 -0.141  3.304 18.695

Coefficients:
                                 Estimate Std. Error t value Pr(>|t|)
(Intercept)                        8.1273     0.3335   24.37  < 2e-16 ***
factor(pathfrac_presentation)yes  -4.6690     1.2517   -3.73 0.000228 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.659 on 308 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.04322,	Adjusted R-squared:  0.04011
F-statistic: 13.91 on 1 and 308 DF,  p-value: 0.0002278
*** summary (lm(mfs_y~factor(margintype),data=csatest))

Call:
lm(formula = mfs_y ~ factor(margintype), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-8.1387 -4.9129 -0.3568  3.3577 16.3994

Coefficients:
                                 Estimate Std. Error t value Pr(>|t|)
(Intercept)                        8.5266     2.5725   3.315  0.00104 **
factor(margintype)gross_positive  -1.6728     3.2792  -0.510  0.61036
factor(margintype)micro_positive  -0.3879     2.6933  -0.144  0.88560
factor(margintype)negative        -0.8739     2.6013  -0.336  0.73715
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.752 on 283 degrees of freedom
  (25 observations deleted due to missingness)
Multiple R-squared:  0.00206,	Adjusted R-squared:  -0.008519
F-statistic: 0.1947 on 3 and 283 DF,  p-value: 0.9
***  summary (lm(mfs_y~factor(tiergrade),data=csatest))

Call:
lm(formula = mfs_y ~ factor(tiergrade), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-8.5319 -4.4313 -0.2118  3.1230 18.4456

Coefficients:
                      Estimate Std. Error t value Pr(>|t|)
(Intercept)             4.5465     0.7693   5.910 9.08e-09 ***
factor(tiergrade)high   3.8297     0.8747   4.378 1.64e-05 ***
factor(tiergrade)low    4.1333     1.0022   4.124 4.80e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.6 on 307 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.06596,	Adjusted R-squared:  0.05987
F-statistic: 10.84 on 2 and 307 DF,  p-value: 2.827e-05
***  summary (lm(mfs_y~factor(body_region),data=csatest))

Call:
lm(formula = mfs_y ~ factor(body_region), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-9.8618 -4.7790 -0.7193  3.3893 19.6775

Coefficients:
                             Estimate Std. Error t value Pr(>|t|)
(Intercept)                    7.1444     0.6094  11.724   <2e-16 ***
factor(body_region)flat_bone   2.7174     1.1717   2.319    0.021 *
factor(body_region)Hand_Foot   1.5827     1.6046   0.986    0.325
factor(body_region)Long_Bone   0.5120     0.7499   0.683    0.495
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.749 on 306 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.01892,	Adjusted R-squared:  0.009297
F-statistic: 1.967 on 3 and 306 DF,  p-value: 0.119


** OS
*** summary(lm(os_y~age_y,data=csatest))

Call:
lm(formula = os_y ~ age_y, data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-9.1209 -4.6182 -0.0079  3.0415 17.6599

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept) 10.91960    0.90543  12.060  < 2e-16 ***
age_y       -0.05436    0.01820  -2.988  0.00304 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.511 on 308 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.02816,	Adjusted R-squared:  0.02501
F-statistic: 8.925 on 1 and 308 DF,  p-value: 0.003038
*** summary(lm(os_y~factor(pathfrac_presentation),data=csatest))

Call:
lm(formula = os_y ~ factor(pathfrac_presentation), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-8.6216 -4.1490 -0.0435  2.9058 18.1538

Coefficients:
                                 Estimate Std. Error t value Pr(>|t|)
(Intercept)                        8.6681     0.3233  26.812  < 2e-16 ***
factor(pathfrac_presentation)yes  -4.1890     1.1888  -3.524  0.00049 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.486 on 309 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.03863,	Adjusted R-squared:  0.03552
F-statistic: 12.42 on 1 and 309 DF,  p-value: 0.0004898
**
*** summary(lm(os_y~factor(margintype),data=csatest))

Call:
lm(formula = os_y ~ factor(margintype), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-8.2846 -4.7154  0.0278  3.1648 15.7209

Coefficients:
                                 Estimate Std. Error t value Pr(>|t|)
(Intercept)                        9.1764     2.4883   3.688 0.000271 ***
factor(margintype)gross_positive  -2.1696     3.1720  -0.684 0.494542
factor(margintype)micro_positive  -0.7481     2.6052  -0.287 0.774203
factor(margintype)negative        -0.8453     2.5160  -0.336 0.737143
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.564 on 284 degrees of freedom
  (24 observations deleted due to missingness)
Multiple R-squared:  0.002053,	Adjusted R-squared:  -0.008489
F-statistic: 0.1948 on 3 and 284 DF,  p-value: 0.8999
*** summary(lm(os_y~factor(tiergrade),data=csatest))

Call:
lm(formula = os_y ~ factor(tiergrade), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-8.8408 -4.5453  0.0666  2.8680 17.9345

Coefficients:
                      Estimate Std. Error t value Pr(>|t|)
(Intercept)             5.7878     0.7529   7.688 2.03e-13 ***
factor(tiergrade)high   3.0996     0.8555   3.623  0.00034 ***
factor(tiergrade)low    3.0963     0.9809   3.157  0.00175 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.481 on 308 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.04363,	Adjusted R-squared:  0.03742
F-statistic: 7.026 on 2 and 308 DF,  p-value: 0.001038
***  summary(lm(os_y~factor(body_region),data=csatest))

Call:
lm(formula = os_y ~ factor(body_region), data = csatest)

Residuals:
    Min      1Q  Median      3Q     Max
-9.4090 -4.6963 -0.7929  3.3886 18.8414

Coefficients:
                             Estimate Std. Error t value Pr(>|t|)
(Intercept)                   7.98055    0.58617  13.615   <2e-16 ***
factor(body_region)flat_bone  2.03390    1.13167   1.797   0.0733 .
factor(body_region)Hand_Foot  2.42566    1.55086   1.564   0.1188
factor(body_region)Long_Bone  0.08087    0.72274   0.112   0.9110
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.561 on 307 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.01876,	Adjusted R-squared:  0.009172
F-statistic: 1.957 on 3 and 307 DF,  p-value: 0.1205
* Cox Modelling
 csacox <- coxph(Surv(lrfs_y,lrstatus)~ factor(type_chondrosarcoma)+ factor(body_region) +factor(tiergrade)+factor(margintype)+factor(pathfrac_presentation)+age_y,data = csa)
Warning message:
In fitter(X, Y, strats, offset, init, control, weights = weights,  :
  Loglik converged before variable  3,5,6,10,11,12 ; beta may be infinite.

> summary(csacox)
Call:
coxph(formula = Surv(lrfs_y, lrstatus) ~ factor(type_chondrosarcoma) +
    factor(body_region) + factor(tiergrade) + factor(margintype) +
    factor(pathfrac_presentation) + age_y, data = csa)

  n= 287, number of events= 29
   (25 observations deleted due to missingness)

                                                      coef  exp(coef)
factor(type_chondrosarcoma)primary_clearcell    -1.296e+00  2.738e-01
factor(type_chondrosarcoma)primary_conventional -1.111e+00  3.293e-01
factor(type_chondrosarcoma)primary_mesenchymal  -1.945e+01  3.570e-09
factor(type_chondrosarcoma)secondary            -1.077e+00  3.404e-01
factor(body_region)flat_bone                    -1.919e+01  4.639e-09
factor(body_region)Hand_Foot                    -1.893e+01  5.999e-09
factor(body_region)Long_Bone                    -3.112e-01  7.325e-01
factor(tiergrade)high                            5.353e-01  1.708e+00
factor(tiergrade)low                             3.098e-01  1.363e+00
factor(margintype)gross_positive                 1.991e+01  4.420e+08
factor(margintype)micro_positive                 1.899e+01  1.761e+08
factor(margintype)negative                       1.856e+01  1.151e+08
factor(pathfrac_presentation)yes                 2.266e+00  9.640e+00
age_y                                            2.968e-02  1.030e+00
                                                  se(coef)      z Pr(>|z|)
factor(type_chondrosarcoma)primary_clearcell     1.469e+00 -0.882   0.3778
factor(type_chondrosarcoma)primary_conventional  9.646e-01 -1.152   0.2494
factor(type_chondrosarcoma)primary_mesenchymal   1.384e+04 -0.001   0.9989
factor(type_chondrosarcoma)secondary             1.067e+00 -1.010   0.3127
factor(body_region)flat_bone                     7.046e+03 -0.003   0.9978
factor(body_region)Hand_Foot                     7.871e+03 -0.002   0.9981
factor(body_region)Long_Bone                     4.313e-01 -0.722   0.4705
factor(tiergrade)high                            7.649e-01  0.700   0.4840
factor(tiergrade)low                             8.904e-01  0.348   0.7279
factor(margintype)gross_positive                 1.866e+04  0.001   0.9991
factor(margintype)micro_positive                 1.866e+04  0.001   0.9992
factor(margintype)negative                       1.866e+04  0.001   0.9992
factor(pathfrac_presentation)yes                 4.919e-01  4.607 4.09e-06 ***
age_y                                            1.310e-02  2.266   0.0234 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

                                                exp(coef) exp(-coef) lower .95
factor(type_chondrosarcoma)primary_clearcell    2.738e-01  3.653e+00   0.01538
factor(type_chondrosarcoma)primary_conventional 3.293e-01  3.037e+00   0.04972
factor(type_chondrosarcoma)primary_mesenchymal  3.570e-09  2.801e+08   0.00000
factor(type_chondrosarcoma)secondary            3.404e-01  2.937e+00   0.04204
factor(body_region)flat_bone                    4.639e-09  2.155e+08   0.00000
factor(body_region)Hand_Foot                    5.999e-09  1.667e+08   0.00000
factor(body_region)Long_Bone                    7.325e-01  1.365e+00   0.31458
factor(tiergrade)high                           1.708e+00  5.855e-01   0.38140
factor(tiergrade)low                            1.363e+00  7.336e-01   0.23805
factor(margintype)gross_positive                4.420e+08  2.262e-09   0.00000
factor(margintype)micro_positive                1.761e+08  5.680e-09   0.00000
factor(margintype)negative                      1.151e+08  8.689e-09   0.00000
factor(pathfrac_presentation)yes                9.640e+00  1.037e-01   3.67619
age_y                                           1.030e+00  9.708e-01   1.00402
                                                upper .95
factor(type_chondrosarcoma)primary_clearcell        4.872
factor(type_chondrosarcoma)primary_conventional     2.181
factor(type_chondrosarcoma)primary_mesenchymal        Inf
factor(type_chondrosarcoma)secondary                2.757
factor(body_region)flat_bone                          Inf
factor(body_region)Hand_Foot                          Inf
factor(body_region)Long_Bone                        1.706
factor(tiergrade)high                               7.649
factor(tiergrade)low                                7.806
factor(margintype)gross_positive                      Inf
factor(margintype)micro_positive                      Inf
factor(margintype)negative                            Inf
factor(pathfrac_presentation)yes                   25.278
age_y                                               1.057

Concordance= 0.809  (se = 0.055 )
Rsquare= 0.153   (max possible= 0.661 )
Likelihood ratio test= 47.55  on 14 df,   p=1.561e-05
Wald test            = 29.88  on 14 df,   p=0.007916
Score (logrank) test = 69.04  on 14 df,   p=2.88e-09
